Repository blackfyre/wga, pull requests merged in 2023-12, with the labels that each got.

#73 Artwork search optimalization
  assets/views/pages/artworks.html
  assets/views/partials/artworks_results.html
  assets/views/partials/nav.html
  docs/searchpage.md
  handlers/artists.go
  handlers/artworks/filters.go
  handlers/artworks/getters.go
  handlers/artworks/main.go
  handlers/main.go
  handlers/search/filters.go
  handlers/search/main.go
  utils/pagination.go
Labels: enhancement

#79 Fix/pb 0.20.0 update
  assets/internals.go
  handlers/artist.go
  handlers/artists.go
  handlers/contributors.go
  handlers/feedback.go
  handlers/guestbook.go
  handlers/home.go
  handlers/postcard.go
  handlers/static.go
  main.go
Labels: bug, enhancement, dependencies

#80 66 fix code scanning alert potentially unsafe external link
  assets/views/pages/contributors.html
  handlers/contributors.go
Labels: bug

#81 55 guestbook not available in direct navigation
  assets/internals.go
  handlers/guestbook.go
Labels: bug

#36 Musicplayer
  .gitignore
  assets/internals.go
  assets/reference/musics.json
  assets/reference/strings.json
  assets/views/layout.html
  assets/views/layouts/layout.html
  assets/views/layouts/noLayout.html
  assets/views/pages/musics.html
  assets/views/pages/musics/music.html
  go.mod
  go.sum
  handlers/main.go
  handlers/musics.go
  main.go
  migrations/1698736507_add_music_tables.go
  models/composers.go
  models/songs.go
  musicUrls.json
  resources/js/app.js
  utils/listMusicUrls.go
  utils/main.go
Labels: enhancement
